server:
  port: 8082

spring:
  application:
    name: citizen-service
---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vaccinationdb
    username: testuser
    password: test123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect